#############################################################################
# Makefile for building: cuACS
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  cuACS.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile cuACS.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cuACS1.0.0
DISTDIR = /home/student/D3/.tmp/cuACS1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		staffMainWindow.cpp \
		overallControl.cpp \
		User.cpp \
		addAnimalDialog.cpp \
		addClientDialog.cpp \
		viewClientWidget.cpp \
		viewAnimalWidget.cpp \
		detailedAnimalDialog.cpp \
		staffDatabaseControl.cpp \
		databaseControl.cpp \
		queryControl.cpp \
		dataModel.cpp \
		dataModelControl.cpp \
		subject.cpp \
		observer.cpp \
		proxySubject.cpp \
		proxy.cpp \
		loginDialog.cpp \
		clientMainWindow.cpp \
		viewEditClientDialog.cpp \
		clientDatabaseControl.cpp moc_overallControl.cpp \
		moc_staffMainWindow.cpp \
		moc_addAnimalDialog.cpp \
		moc_addClientDialog.cpp \
		moc_viewClientWidget.cpp \
		moc_viewAnimalWidget.cpp \
		moc_detailedAnimalDialog.cpp \
		moc_staffDatabaseControl.cpp \
		moc_databaseControl.cpp \
		moc_dataModel.cpp \
		moc_dataModelControl.cpp \
		moc_subject.cpp \
		moc_observer.cpp \
		moc_proxySubject.cpp \
		moc_proxy.cpp \
		moc_loginDialog.cpp \
		moc_clientMainWindow.cpp \
		moc_viewEditClientDialog.cpp \
		moc_clientDatabaseControl.cpp
OBJECTS       = main.o \
		staffMainWindow.o \
		overallControl.o \
		User.o \
		addAnimalDialog.o \
		addClientDialog.o \
		viewClientWidget.o \
		viewAnimalWidget.o \
		detailedAnimalDialog.o \
		staffDatabaseControl.o \
		databaseControl.o \
		queryControl.o \
		dataModel.o \
		dataModelControl.o \
		subject.o \
		observer.o \
		proxySubject.o \
		proxy.o \
		loginDialog.o \
		clientMainWindow.o \
		viewEditClientDialog.o \
		clientDatabaseControl.o \
		moc_overallControl.o \
		moc_staffMainWindow.o \
		moc_addAnimalDialog.o \
		moc_addClientDialog.o \
		moc_viewClientWidget.o \
		moc_viewAnimalWidget.o \
		moc_detailedAnimalDialog.o \
		moc_staffDatabaseControl.o \
		moc_databaseControl.o \
		moc_dataModel.o \
		moc_dataModelControl.o \
		moc_subject.o \
		moc_observer.o \
		moc_proxySubject.o \
		moc_proxy.o \
		moc_loginDialog.o \
		moc_clientMainWindow.o \
		moc_viewEditClientDialog.o \
		moc_clientDatabaseControl.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro overallControl.h \
		staffMainWindow.h \
		User.h \
		addAnimalDialog.h \
		addClientDialog.h \
		viewClientWidget.h \
		viewAnimalWidget.h \
		detailedAnimalDialog.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModel.h \
		dataModelControl.h \
		subject.h \
		observer.h \
		proxySubject.h \
		proxy.h \
		loginDialog.h \
		clientMainWindow.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h main.cpp \
		staffMainWindow.cpp \
		overallControl.cpp \
		User.cpp \
		addAnimalDialog.cpp \
		addClientDialog.cpp \
		viewClientWidget.cpp \
		viewAnimalWidget.cpp \
		detailedAnimalDialog.cpp \
		staffDatabaseControl.cpp \
		databaseControl.cpp \
		queryControl.cpp \
		dataModel.cpp \
		dataModelControl.cpp \
		subject.cpp \
		observer.cpp \
		proxySubject.cpp \
		proxy.cpp \
		loginDialog.cpp \
		clientMainWindow.cpp \
		viewEditClientDialog.cpp \
		clientDatabaseControl.cpp
QMAKE_TARGET  = cuACS
DESTDIR       = 
TARGET        = cuACS


first: all
####### Build rules

$(TARGET): ui_staffMainWindow.h ui_addAnimalDialog.h ui_addClientDialog.h ui_viewClientWidget.h ui_viewAnimalWidget.h ui_loginDialog.h ui_clientMainWindow.h ui_viewEditClientDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: cuACS.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		cuACS.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile cuACS.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3danimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dcore.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dlogic.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickanimation.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickextras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickinput.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickrender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_3drender.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
cuACS.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cuACS.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents overallControl.h staffMainWindow.h User.h addAnimalDialog.h addClientDialog.h viewClientWidget.h viewAnimalWidget.h detailedAnimalDialog.h staffDatabaseControl.h databaseControl.h queryControl.h dataModel.h dataModelControl.h subject.h observer.h proxySubject.h proxy.h loginDialog.h clientMainWindow.h viewEditClientDialog.h clientDatabaseControl.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp staffMainWindow.cpp overallControl.cpp User.cpp addAnimalDialog.cpp addClientDialog.cpp viewClientWidget.cpp viewAnimalWidget.cpp detailedAnimalDialog.cpp staffDatabaseControl.cpp databaseControl.cpp queryControl.cpp dataModel.cpp dataModelControl.cpp subject.cpp observer.cpp proxySubject.cpp proxy.cpp loginDialog.cpp clientMainWindow.cpp viewEditClientDialog.cpp clientDatabaseControl.cpp $(DISTDIR)/
	$(COPY_FILE) --parents staffMainWindow.ui addAnimalDialog.ui addClientDialog.ui viewClientWidget.ui viewAnimalWidget.ui loginDialog.ui clientMainWindow.ui viewEditClientDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_overallControl.cpp moc_staffMainWindow.cpp moc_addAnimalDialog.cpp moc_addClientDialog.cpp moc_viewClientWidget.cpp moc_viewAnimalWidget.cpp moc_detailedAnimalDialog.cpp moc_staffDatabaseControl.cpp moc_databaseControl.cpp moc_dataModel.cpp moc_dataModelControl.cpp moc_subject.cpp moc_observer.cpp moc_proxySubject.cpp moc_proxy.cpp moc_loginDialog.cpp moc_clientMainWindow.cpp moc_viewEditClientDialog.cpp moc_clientDatabaseControl.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_overallControl.cpp moc_staffMainWindow.cpp moc_addAnimalDialog.cpp moc_addClientDialog.cpp moc_viewClientWidget.cpp moc_viewAnimalWidget.cpp moc_detailedAnimalDialog.cpp moc_staffDatabaseControl.cpp moc_databaseControl.cpp moc_dataModel.cpp moc_dataModelControl.cpp moc_subject.cpp moc_observer.cpp moc_proxySubject.cpp moc_proxy.cpp moc_loginDialog.cpp moc_clientMainWindow.cpp moc_viewEditClientDialog.cpp moc_clientDatabaseControl.cpp
moc_overallControl.cpp: proxy.h \
		proxySubject.h \
		staffMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		clientMainWindow.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		loginDialog.h \
		overallControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include overallControl.h -o moc_overallControl.cpp

moc_staffMainWindow.cpp: viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		proxySubject.h \
		staffMainWindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include staffMainWindow.h -o moc_staffMainWindow.cpp

moc_addAnimalDialog.cpp: staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		subject.h \
		observer.h \
		addAnimalDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include addAnimalDialog.h -o moc_addAnimalDialog.cpp

moc_addClientDialog.cpp: staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		subject.h \
		observer.h \
		addClientDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include addClientDialog.h -o moc_addClientDialog.cpp

moc_viewClientWidget.cpp: ui_viewClientWidget.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		viewClientWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewClientWidget.h -o moc_viewClientWidget.cpp

moc_viewAnimalWidget.cpp: ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewAnimalWidget.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewAnimalWidget.h -o moc_viewAnimalWidget.cpp

moc_detailedAnimalDialog.cpp: detailedAnimalDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include detailedAnimalDialog.h -o moc_detailedAnimalDialog.cpp

moc_staffDatabaseControl.cpp: databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		staffDatabaseControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include staffDatabaseControl.h -o moc_staffDatabaseControl.cpp

moc_databaseControl.cpp: queryControl.h \
		databaseControl.h \
		dataModelControl.h \
		dataModel.h \
		databaseControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include databaseControl.h -o moc_databaseControl.cpp

moc_dataModel.cpp: dataModel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dataModel.h -o moc_dataModel.cpp

moc_dataModelControl.cpp: dataModel.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModelControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include dataModelControl.h -o moc_dataModelControl.cpp

moc_subject.cpp: observer.h \
		subject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include subject.h -o moc_subject.cpp

moc_observer.cpp: observer.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include observer.h -o moc_observer.cpp

moc_proxySubject.cpp: proxySubject.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include proxySubject.h -o moc_proxySubject.cpp

moc_proxy.cpp: proxySubject.h \
		staffMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		clientMainWindow.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		loginDialog.h \
		proxy.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include proxy.h -o moc_proxy.cpp

moc_loginDialog.cpp: loginDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include loginDialog.h -o moc_loginDialog.cpp

moc_clientMainWindow.cpp: viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		clientMainWindow.h \
		proxySubject.h \
		clientMainWindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clientMainWindow.h -o moc_clientMainWindow.cpp

moc_viewEditClientDialog.cpp: clientDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		clientMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		staffDatabaseControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewEditClientDialog.h \
		proxySubject.h \
		viewEditClientDialog.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include viewEditClientDialog.h -o moc_viewEditClientDialog.cpp

moc_clientDatabaseControl.cpp: databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		clientMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		staffDatabaseControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		proxySubject.h \
		clientDatabaseControl.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/student/D3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include clientDatabaseControl.h -o moc_clientDatabaseControl.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_staffMainWindow.h ui_addAnimalDialog.h ui_addClientDialog.h ui_viewClientWidget.h ui_viewAnimalWidget.h ui_loginDialog.h ui_clientMainWindow.h ui_viewEditClientDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_staffMainWindow.h ui_addAnimalDialog.h ui_addClientDialog.h ui_viewClientWidget.h ui_viewAnimalWidget.h ui_loginDialog.h ui_clientMainWindow.h ui_viewEditClientDialog.h
ui_staffMainWindow.h: staffMainWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic staffMainWindow.ui -o ui_staffMainWindow.h

ui_addAnimalDialog.h: addAnimalDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic addAnimalDialog.ui -o ui_addAnimalDialog.h

ui_addClientDialog.h: addClientDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic addClientDialog.ui -o ui_addClientDialog.h

ui_viewClientWidget.h: viewClientWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic viewClientWidget.ui -o ui_viewClientWidget.h

ui_viewAnimalWidget.h: viewAnimalWidget.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic viewAnimalWidget.ui -o ui_viewAnimalWidget.h

ui_loginDialog.h: loginDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic loginDialog.ui -o ui_loginDialog.h

ui_clientMainWindow.h: clientMainWindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic clientMainWindow.ui -o ui_clientMainWindow.h

ui_viewEditClientDialog.h: viewEditClientDialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic viewEditClientDialog.ui -o ui_viewEditClientDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp overallControl.h \
		proxy.h \
		proxySubject.h \
		staffMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		clientMainWindow.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		loginDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

staffMainWindow.o: staffMainWindow.cpp staffMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		proxySubject.h \
		ui_staffMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staffMainWindow.o staffMainWindow.cpp

overallControl.o: overallControl.cpp overallControl.h \
		proxy.h \
		proxySubject.h \
		staffMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		clientMainWindow.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		loginDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o overallControl.o overallControl.cpp

User.o: User.cpp User.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

addAnimalDialog.o: addAnimalDialog.cpp addAnimalDialog.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		subject.h \
		observer.h \
		ui_addAnimalDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addAnimalDialog.o addAnimalDialog.cpp

addClientDialog.o: addClientDialog.cpp addClientDialog.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		subject.h \
		observer.h \
		ui_addClientDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o addClientDialog.o addClientDialog.cpp

viewClientWidget.o: viewClientWidget.cpp viewClientWidget.h \
		ui_viewClientWidget.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewClientWidget.o viewClientWidget.cpp

viewAnimalWidget.o: viewAnimalWidget.cpp viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewAnimalWidget.o viewAnimalWidget.cpp

detailedAnimalDialog.o: detailedAnimalDialog.cpp detailedAnimalDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o detailedAnimalDialog.o detailedAnimalDialog.cpp

staffDatabaseControl.o: staffDatabaseControl.cpp staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o staffDatabaseControl.o staffDatabaseControl.cpp

databaseControl.o: databaseControl.cpp databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databaseControl.o databaseControl.cpp

queryControl.o: queryControl.cpp queryControl.h \
		databaseControl.h \
		dataModelControl.h \
		dataModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryControl.o queryControl.cpp

dataModel.o: dataModel.cpp dataModel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataModel.o dataModel.cpp

dataModelControl.o: dataModelControl.cpp dataModelControl.h \
		dataModel.h \
		databaseControl.h \
		queryControl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dataModelControl.o dataModelControl.cpp

subject.o: subject.cpp subject.h \
		observer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o subject.o subject.cpp

observer.o: observer.cpp observer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o observer.o observer.cpp

proxySubject.o: proxySubject.cpp proxySubject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proxySubject.o proxySubject.cpp

proxy.o: proxy.cpp proxy.h \
		proxySubject.h \
		staffMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewClientWidget.h \
		ui_viewClientWidget.h \
		addClientDialog.h \
		clientMainWindow.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		loginDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o proxy.o proxy.cpp

loginDialog.o: loginDialog.cpp loginDialog.h \
		ui_loginDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loginDialog.o loginDialog.cpp

clientMainWindow.o: clientMainWindow.cpp clientMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		dataModel.h \
		staffDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewEditClientDialog.h \
		clientDatabaseControl.h \
		proxySubject.h \
		ui_clientMainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientMainWindow.o clientMainWindow.cpp

viewEditClientDialog.o: viewEditClientDialog.cpp viewEditClientDialog.h \
		clientDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		clientMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		staffDatabaseControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		proxySubject.h \
		ui_viewEditClientDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewEditClientDialog.o viewEditClientDialog.cpp

clientDatabaseControl.o: clientDatabaseControl.cpp clientDatabaseControl.h \
		databaseControl.h \
		queryControl.h \
		dataModelControl.h \
		dataModel.h \
		clientMainWindow.h \
		viewAnimalWidget.h \
		ui_viewAnimalWidget.h \
		detailedAnimalDialog.h \
		staffDatabaseControl.h \
		observer.h \
		addAnimalDialog.h \
		subject.h \
		viewEditClientDialog.h \
		proxySubject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o clientDatabaseControl.o clientDatabaseControl.cpp

moc_overallControl.o: moc_overallControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_overallControl.o moc_overallControl.cpp

moc_staffMainWindow.o: moc_staffMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_staffMainWindow.o moc_staffMainWindow.cpp

moc_addAnimalDialog.o: moc_addAnimalDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addAnimalDialog.o moc_addAnimalDialog.cpp

moc_addClientDialog.o: moc_addClientDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_addClientDialog.o moc_addClientDialog.cpp

moc_viewClientWidget.o: moc_viewClientWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewClientWidget.o moc_viewClientWidget.cpp

moc_viewAnimalWidget.o: moc_viewAnimalWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewAnimalWidget.o moc_viewAnimalWidget.cpp

moc_detailedAnimalDialog.o: moc_detailedAnimalDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_detailedAnimalDialog.o moc_detailedAnimalDialog.cpp

moc_staffDatabaseControl.o: moc_staffDatabaseControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_staffDatabaseControl.o moc_staffDatabaseControl.cpp

moc_databaseControl.o: moc_databaseControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databaseControl.o moc_databaseControl.cpp

moc_dataModel.o: moc_dataModel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataModel.o moc_dataModel.cpp

moc_dataModelControl.o: moc_dataModelControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dataModelControl.o moc_dataModelControl.cpp

moc_subject.o: moc_subject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_subject.o moc_subject.cpp

moc_observer.o: moc_observer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_observer.o moc_observer.cpp

moc_proxySubject.o: moc_proxySubject.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_proxySubject.o moc_proxySubject.cpp

moc_proxy.o: moc_proxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_proxy.o moc_proxy.cpp

moc_loginDialog.o: moc_loginDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loginDialog.o moc_loginDialog.cpp

moc_clientMainWindow.o: moc_clientMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientMainWindow.o moc_clientMainWindow.cpp

moc_viewEditClientDialog.o: moc_viewEditClientDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_viewEditClientDialog.o moc_viewEditClientDialog.cpp

moc_clientDatabaseControl.o: moc_clientDatabaseControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_clientDatabaseControl.o moc_clientDatabaseControl.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

